name: deploy davidtw.co

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Unlock secrets
        uses: alexburlton-sonocent/github-action-git-crypt-unlock@quote-env-var
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Install Nix
        uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          skip_adding_nixpkgs_channel: true

      - name: Build website
        run: cp -R "$(nix-build ./compat.nix -A defaultNix --no-out-link)" result

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=result --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
